server {
    listen [::]:80;
    server_name www.google.com;

    root   /usr/share/nginx/html/google;
    index  index.php;

    error_page  404 =200 /default.php;

    return 301 https://$server_name$request_uri;
}


server {
    listen [::]:443 ssl;
    server_name www.google.com;

    ssl_certificate /usr/share/nginx/html/google/.cert/cert.pem;
    ssl_certificate_key /usr/share/nginx/html/google/.cert/key.pem;

    root   /usr/share/nginx/html/google;
    index  index.php;

    error_page  404 =200 /default.php;

    location @extensionless-php {

        rewrite ^(.*)$ $1.php last;

    }

    location / {

        try_files $uri $uri/ @extensionless-php;
#        fastcgi_intercept_errors off;

    }

    location ~ \.php$ {
#        root           google;
	try_files $uri =404;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}
